export const ACTION_TYPE = {
	CLOSE_MODAL: 'CLOSE_MODAL',
	CLOSE_TASK: 'CLOSE_TASK',
	LOGOUT: 'LOGOUT',
	OPEN_MODAL: 'OPEN_MODAL',
	OPEN_TASK: 'OPEN_TASK',
	SET_PROJECT_DATA: 'SET_PROJECT_DATA',
	SET_SESSION: 'SET_SESSION',
	SET_TASKS: 'SET_TASKS',
	SET_TASK_DATA: 'SET_TASK_DATA',
	SET_USER: 'SET_USER',
	SET_USERS: 'SET_USERS',
};
