export const ACTION_TYPE = {
	CLOSE_MODAL: 'CLOSE_MODAL',
	LOGOUT: 'LOGOUT',
	OPEN_MODAL: 'OPEN_MODAL',
	SET_PROJECT_DATA: 'SET_PROJECT_DATA',
	SET_SESSION: 'SET_SESSION',
	SET_TASKS: 'SET_TASKS',
	SET_USER: 'SET_USER',
	SET_USERS: 'SET_USERS',
};
